# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WeatherApp(object):
    def setupUi(self, WeatherApp):
        WeatherApp.setObjectName("WeatherApp")
        WeatherApp.resize(1000, 750)
        WeatherApp.setStyleSheet("/* 🌿 Nền màu xanh-xám nhẹ */\n"
"    QWidget {\n"
"        font-family: Arial, sans-serif;\n"
"        font-size: 14px;\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                    stop:0 #E0EAFC, stop:1 #CFDEF3); /* Gradient xanh-xám nhẹ */\n"
"    }\n"
"\n"
"    QLabel {\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"    /* 🕒 Thời gian & Địa điểm - làm nổi bật hơn */\n"
"    QLabel#label_time, QLabel#label_location {\n"
"        font-size: 22px;\n"
"        font-weight: bold;\n"
"        color: #ffffff;\n"
"        background-color: rgba(0, 0, 0, 0.5); /* Nền trong suốt nhẹ */\n"
"        border-radius: 10px;\n"
"        padding: 12px;\n"
"        text-align: center;\n"
"    }\n"
"\n"
"    /* 🔍 Ô tìm kiếm */\n"
"    QLineEdit#lineEdit_city_search {\n"
"        font-size: 18px;\n"
"        padding: 10px;\n"
"        border: 2px solid #4A90E2;\n"
"        border-radius: 25px;\n"
"        background-color: rgba(255, 255, 255, 0.9);\n"
"        color: #333;\n"
"    }\n"
"\n"
"    /* Căn giữa placeholder */\n"
"    QLineEdit#lineEdit_city_search::placeholder {\n"
"        text-align: center;\n"
"        font-style: italic;\n"
"        color: #666;\n"
"    }\n"
"\n"
"    /* 🎯 Nút tìm kiếm */\n"
"    QPushButton#btn_search {\n"
"        background-color: #4A90E2;\n"
"        color: white;\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        border-radius: 25px;\n"
"        padding: 8px;\n"
"    }\n"
"\n"
"    QPushButton#btn_search:hover {\n"
"        background-color: #357ABD;\n"
"    }\n"
"\n"
"    /* 🌤 Khung dự báo thời tiết */\n"
"    QFrame#forecast_container {\n"
"        max-width: 920px;\n"
"        min-height: 180px;\n"
"        padding: 5px;\n"
"    }\n"
"\n"
"    QFrame#forecast_container > QFrame {\n"
"        min-width: 130px;\n"
"        max-width: 140px;\n"
"        min-height: 180px;\n"
"        margin: 8px;\n"
"        padding: 10px;\n"
"        background: rgba(255, 255, 255, 0.95);\n"
"        border: 2px solid #4A90E2;\n"
"        border-radius: 12px;\n"
"        text-align: center;\n"
"        box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.15);\n"
"    }\n"
"\n"
"    QLabel#label_day1, QLabel#label_day2, QLabel#label_day3,\n"
"    QLabel#label_day4, QLabel#label_day5, QLabel#label_day6, QLabel#label_day7 {\n"
"        font-weight: bold;\n"
"        font-size: 16px;\n"
"        text-align: center;\n"
"        color: #4A90E2;\n"
"    }\n"
"\n"
"    QLabel#label_temp1, QLabel#label_temp2, QLabel#label_temp3,\n"
"    QLabel#label_temp4, QLabel#label_temp5, QLabel#label_temp6, QLabel#label_temp7 {\n"
"        font-size: 14px;\n"
"        color: #333;\n"
"    }\n"
"\n"
"    QLabel#label_rain1, QLabel#label_rain2, QLabel#label_rain3,\n"
"    QLabel#label_rain4, QLabel#label_rain5, QLabel#label_rain6, QLabel#label_rain7 {\n"
"        font-size: 14px;\n"
"        font-weight: bold;\n"
"        color: #357ABD;\n"
"    }\n"
"\n"
"    /* ⚠️ Cảnh báo thời tiết */\n"
"    QLabel#label_weather_alert {\n"
"        background-color: rgba(255, 102, 102, 0.9);\n"
"        padding: 12px;\n"
"        border-radius: 8px;\n"
"        font-weight: bold;\n"
"        font-size: 16px;\n"
"        color: white;\n"
"    }")
        self.centralwidget = QtWidgets.QWidget(parent=WeatherApp)
        self.centralwidget.setObjectName("centralwidget")
        self.label_time = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(30, 20, 180, 60))
        self.label_time.setObjectName("label_time")
        self.label_location = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_location.setGeometry(QtCore.QRect(749, 20, 211, 60))
        self.label_location.setObjectName("label_location")
        self.lineEdit_city_search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_city_search.setGeometry(QtCore.QRect(320, 90, 300, 50))
        self.lineEdit_city_search.setObjectName("lineEdit_city_search")
        self.btn_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(630, 90, 60, 50))
        self.btn_search.setObjectName("btn_search")
        self.frame_current_weather = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_current_weather.setGeometry(QtCore.QRect(30, 160, 280, 220))
        self.frame_current_weather.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_current_weather.setObjectName("frame_current_weather")
        self.verticalLayout_weather = QtWidgets.QVBoxLayout(self.frame_current_weather)
        self.verticalLayout_weather.setObjectName("verticalLayout_weather")
        self.label_temperature = QtWidgets.QLabel(parent=self.frame_current_weather)
        self.label_temperature.setObjectName("label_temperature")
        self.verticalLayout_weather.addWidget(self.label_temperature)
        self.label_humidity = QtWidgets.QLabel(parent=self.frame_current_weather)
        self.label_humidity.setObjectName("label_humidity")
        self.verticalLayout_weather.addWidget(self.label_humidity)
        self.label_pressure = QtWidgets.QLabel(parent=self.frame_current_weather)
        self.label_pressure.setObjectName("label_pressure")
        self.verticalLayout_weather.addWidget(self.label_pressure)
        self.label_wind_speed = QtWidgets.QLabel(parent=self.frame_current_weather)
        self.label_wind_speed.setObjectName("label_wind_speed")
        self.verticalLayout_weather.addWidget(self.label_wind_speed)
        self.label_uv_index = QtWidgets.QLabel(parent=self.frame_current_weather)
        self.label_uv_index.setObjectName("label_uv_index")
        self.verticalLayout_weather.addWidget(self.label_uv_index)
        self.label_weather_description = QtWidgets.QLabel(parent=self.frame_current_weather)
        self.label_weather_description.setObjectName("label_weather_description")
        self.verticalLayout_weather.addWidget(self.label_weather_description)
        self.frame_chart = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_chart.setGeometry(QtCore.QRect(330, 160, 600, 220))
        self.frame_chart.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_chart.setObjectName("frame_chart")
        self.forecast_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.forecast_container.setGeometry(QtCore.QRect(30, 400, 920, 180))
        self.forecast_container.setObjectName("forecast_container")
        self.forecast_layout = QtWidgets.QHBoxLayout(self.forecast_container)
        self.forecast_layout.setContentsMargins(0, 0, 0, 0)
        self.forecast_layout.setObjectName("forecast_layout")
        self.frame_day1 = QtWidgets.QFrame(parent=self.forecast_container)
        self.frame_day1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_day1.setObjectName("frame_day1")
        self.layout_day1 = QtWidgets.QVBoxLayout(self.frame_day1)
        self.layout_day1.setObjectName("layout_day1")
        self.label_day1 = QtWidgets.QLabel(parent=self.frame_day1)
        self.label_day1.setObjectName("label_day1")
        self.layout_day1.addWidget(self.label_day1)
        self.label_temp1 = QtWidgets.QLabel(parent=self.frame_day1)
        self.label_temp1.setObjectName("label_temp1")
        self.layout_day1.addWidget(self.label_temp1)
        self.label_icon1 = QtWidgets.QLabel(parent=self.frame_day1)
        self.label_icon1.setObjectName("label_icon1")
        self.layout_day1.addWidget(self.label_icon1)
        self.label_rain1 = QtWidgets.QLabel(parent=self.frame_day1)
        self.label_rain1.setObjectName("label_rain1")
        self.layout_day1.addWidget(self.label_rain1)
        self.forecast_layout.addWidget(self.frame_day1)
        self.frame_day2 = QtWidgets.QFrame(parent=self.forecast_container)
        self.frame_day2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_day2.setObjectName("frame_day2")
        self.layout_day2 = QtWidgets.QVBoxLayout(self.frame_day2)
        self.layout_day2.setObjectName("layout_day2")
        self.label_day2 = QtWidgets.QLabel(parent=self.frame_day2)
        self.label_day2.setObjectName("label_day2")
        self.layout_day2.addWidget(self.label_day2)
        self.label_temp2 = QtWidgets.QLabel(parent=self.frame_day2)
        self.label_temp2.setObjectName("label_temp2")
        self.layout_day2.addWidget(self.label_temp2)
        self.label_icon2 = QtWidgets.QLabel(parent=self.frame_day2)
        self.label_icon2.setObjectName("label_icon2")
        self.layout_day2.addWidget(self.label_icon2)
        self.label_rain2 = QtWidgets.QLabel(parent=self.frame_day2)
        self.label_rain2.setObjectName("label_rain2")
        self.layout_day2.addWidget(self.label_rain2)
        self.forecast_layout.addWidget(self.frame_day2)
        self.frame_day3 = QtWidgets.QFrame(parent=self.forecast_container)
        self.frame_day3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_day3.setObjectName("frame_day3")
        self.layout_day3 = QtWidgets.QVBoxLayout(self.frame_day3)
        self.layout_day3.setObjectName("layout_day3")
        self.label_day3 = QtWidgets.QLabel(parent=self.frame_day3)
        self.label_day3.setObjectName("label_day3")
        self.layout_day3.addWidget(self.label_day3)
        self.label_temp3 = QtWidgets.QLabel(parent=self.frame_day3)
        self.label_temp3.setObjectName("label_temp3")
        self.layout_day3.addWidget(self.label_temp3)
        self.label_icon3 = QtWidgets.QLabel(parent=self.frame_day3)
        self.label_icon3.setObjectName("label_icon3")
        self.layout_day3.addWidget(self.label_icon3)
        self.label_rain3 = QtWidgets.QLabel(parent=self.frame_day3)
        self.label_rain3.setObjectName("label_rain3")
        self.layout_day3.addWidget(self.label_rain3)
        self.forecast_layout.addWidget(self.frame_day3)
        self.frame_day4 = QtWidgets.QFrame(parent=self.forecast_container)
        self.frame_day4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_day4.setObjectName("frame_day4")
        self.layout_day4 = QtWidgets.QVBoxLayout(self.frame_day4)
        self.layout_day4.setObjectName("layout_day4")
        self.label_day4 = QtWidgets.QLabel(parent=self.frame_day4)
        self.label_day4.setObjectName("label_day4")
        self.layout_day4.addWidget(self.label_day4)
        self.label_temp4 = QtWidgets.QLabel(parent=self.frame_day4)
        self.label_temp4.setObjectName("label_temp4")
        self.layout_day4.addWidget(self.label_temp4)
        self.label_icon4 = QtWidgets.QLabel(parent=self.frame_day4)
        self.label_icon4.setObjectName("label_icon4")
        self.layout_day4.addWidget(self.label_icon4)
        self.label_rain4 = QtWidgets.QLabel(parent=self.frame_day4)
        self.label_rain4.setObjectName("label_rain4")
        self.layout_day4.addWidget(self.label_rain4)
        self.forecast_layout.addWidget(self.frame_day4)
        self.frame_day5 = QtWidgets.QFrame(parent=self.forecast_container)
        self.frame_day5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_day5.setObjectName("frame_day5")
        self.layout_day5 = QtWidgets.QVBoxLayout(self.frame_day5)
        self.layout_day5.setObjectName("layout_day5")
        self.label_day5 = QtWidgets.QLabel(parent=self.frame_day5)
        self.label_day5.setObjectName("label_day5")
        self.layout_day5.addWidget(self.label_day5)
        self.label_temp5 = QtWidgets.QLabel(parent=self.frame_day5)
        self.label_temp5.setObjectName("label_temp5")
        self.layout_day5.addWidget(self.label_temp5)
        self.label_icon5 = QtWidgets.QLabel(parent=self.frame_day5)
        self.label_icon5.setObjectName("label_icon5")
        self.layout_day5.addWidget(self.label_icon5)
        self.label_rain5 = QtWidgets.QLabel(parent=self.frame_day5)
        self.label_rain5.setObjectName("label_rain5")
        self.layout_day5.addWidget(self.label_rain5)
        self.forecast_layout.addWidget(self.frame_day5)
        self.frame_day6 = QtWidgets.QFrame(parent=self.forecast_container)
        self.frame_day6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_day6.setObjectName("frame_day6")
        self.layout_day6 = QtWidgets.QVBoxLayout(self.frame_day6)
        self.layout_day6.setObjectName("layout_day6")
        self.label_day6 = QtWidgets.QLabel(parent=self.frame_day6)
        self.label_day6.setObjectName("label_day6")
        self.layout_day6.addWidget(self.label_day6)
        self.label_temp6 = QtWidgets.QLabel(parent=self.frame_day6)
        self.label_temp6.setObjectName("label_temp6")
        self.layout_day6.addWidget(self.label_temp6)
        self.label_icon6 = QtWidgets.QLabel(parent=self.frame_day6)
        self.label_icon6.setObjectName("label_icon6")
        self.layout_day6.addWidget(self.label_icon6)
        self.label_rain6 = QtWidgets.QLabel(parent=self.frame_day6)
        self.label_rain6.setObjectName("label_rain6")
        self.layout_day6.addWidget(self.label_rain6)
        self.forecast_layout.addWidget(self.frame_day6)
        self.frame_day7 = QtWidgets.QFrame(parent=self.forecast_container)
        self.frame_day7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_day7.setObjectName("frame_day7")
        self.layout_day7 = QtWidgets.QVBoxLayout(self.frame_day7)
        self.layout_day7.setObjectName("layout_day7")
        self.label_day7 = QtWidgets.QLabel(parent=self.frame_day7)
        self.label_day7.setObjectName("label_day7")
        self.layout_day7.addWidget(self.label_day7)
        self.label_temp7 = QtWidgets.QLabel(parent=self.frame_day7)
        self.label_temp7.setObjectName("label_temp7")
        self.layout_day7.addWidget(self.label_temp7)
        self.label_icon7 = QtWidgets.QLabel(parent=self.frame_day7)
        self.label_icon7.setObjectName("label_icon7")
        self.layout_day7.addWidget(self.label_icon7)
        self.label_rain7 = QtWidgets.QLabel(parent=self.frame_day7)
        self.label_rain7.setObjectName("label_rain7")
        self.layout_day7.addWidget(self.label_rain7)
        self.forecast_layout.addWidget(self.frame_day7)
        self.label_weather_alert = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_weather_alert.setGeometry(QtCore.QRect(650, 600, 280, 80))
        self.label_weather_alert.setObjectName("label_weather_alert")
        self.frame_clothing_suggestion = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_clothing_suggestion.setGeometry(QtCore.QRect(30, 610, 280, 100))
        self.frame_clothing_suggestion.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_clothing_suggestion.setObjectName("frame_clothing_suggestion")
        self.layout_clothing = QtWidgets.QVBoxLayout(self.frame_clothing_suggestion)
        self.layout_clothing.setObjectName("layout_clothing")
        self.label_clothing_title = QtWidgets.QLabel(parent=self.frame_clothing_suggestion)
        self.label_clothing_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_clothing_title.setObjectName("label_clothing_title")
        self.layout_clothing.addWidget(self.label_clothing_title)
        self.label_clothing_suggestion = QtWidgets.QLabel(parent=self.frame_clothing_suggestion)
        self.label_clothing_suggestion.setWordWrap(True)
        self.label_clothing_suggestion.setObjectName("label_clothing_suggestion")
        self.layout_clothing.addWidget(self.label_clothing_suggestion)
        WeatherApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(WeatherApp)
        QtCore.QMetaObject.connectSlotsByName(WeatherApp)

    def retranslateUi(self, WeatherApp):
        _translate = QtCore.QCoreApplication.translate
        WeatherApp.setWindowTitle(_translate("WeatherApp", "Dự báo thời tiết"))
        self.label_time.setText(_translate("WeatherApp", "01:21 PM"))
        self.label_location.setText(_translate("WeatherApp", "Hà Nội, Việt Nam"))
        self.lineEdit_city_search.setText(_translate("WeatherApp", "Nhập tên thành phố..."))
        self.btn_search.setText(_translate("WeatherApp", "🔍"))
        self.label_temperature.setText(_translate("WeatherApp", "Nhiệt độ: 28°C"))
        self.label_humidity.setText(_translate("WeatherApp", "Độ ẩm: 75%"))
        self.label_pressure.setText(_translate("WeatherApp", "Áp suất: 1008 hPa"))
        self.label_wind_speed.setText(_translate("WeatherApp", "Tốc độ gió: 12 km/h"))
        self.label_uv_index.setText(_translate("WeatherApp", "Chỉ số UV: 6 (Cao)"))
        self.label_weather_description.setText(_translate("WeatherApp", "Trạng thái: Trời nhiều mây ⛅"))
        self.label_day1.setText(_translate("WeatherApp", "Thứ Hai"))
        self.label_temp1.setText(_translate("WeatherApp", "30°C / 25°C"))
        self.label_icon1.setText(_translate("WeatherApp", "☀️"))
        self.label_rain1.setText(_translate("WeatherApp", "10% mưa"))
        self.label_day2.setText(_translate("WeatherApp", "Thứ Ba"))
        self.label_temp2.setText(_translate("WeatherApp", "29°C / 24°C"))
        self.label_icon2.setText(_translate("WeatherApp", "🌤"))
        self.label_rain2.setText(_translate("WeatherApp", "20% mưa"))
        self.label_day3.setText(_translate("WeatherApp", "Thứ Tư"))
        self.label_temp3.setText(_translate("WeatherApp", "27°C / 23°C"))
        self.label_icon3.setText(_translate("WeatherApp", "🌧"))
        self.label_rain3.setText(_translate("WeatherApp", "60% mưa"))
        self.label_day4.setText(_translate("WeatherApp", "Thứ Năm"))
        self.label_temp4.setText(_translate("WeatherApp", "28°C / 24°C"))
        self.label_icon4.setText(_translate("WeatherApp", "⛅"))
        self.label_rain4.setText(_translate("WeatherApp", "30% mưa"))
        self.label_day5.setText(_translate("WeatherApp", "Thứ Sáu"))
        self.label_temp5.setText(_translate("WeatherApp", "31°C / 26°C"))
        self.label_icon5.setText(_translate("WeatherApp", "☀️"))
        self.label_rain5.setText(_translate("WeatherApp", "5% mưa"))
        self.label_day6.setText(_translate("WeatherApp", "Thứ Bảy"))
        self.label_temp6.setText(_translate("WeatherApp", "30°C / 25°C"))
        self.label_icon6.setText(_translate("WeatherApp", "⛈"))
        self.label_rain6.setText(_translate("WeatherApp", "70% mưa"))
        self.label_day7.setText(_translate("WeatherApp", "Chủ Nhật"))
        self.label_temp7.setText(_translate("WeatherApp", "29°C / 24°C"))
        self.label_icon7.setText(_translate("WeatherApp", "🌦"))
        self.label_rain7.setText(_translate("WeatherApp", "40% mưa"))
        self.label_weather_alert.setText(_translate("WeatherApp", "⚠️ Cảnh báo: Mưa dông lúc 15:00"))
        self.label_clothing_title.setText(_translate("WeatherApp", "👕 Gợi ý trang phục hôm nay"))
        self.label_clothing_suggestion.setText(_translate("WeatherApp", "Mang theo áo khoác nhẹ và ô do trời có thể mưa."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WeatherApp = QtWidgets.QMainWindow()
    ui = Ui_WeatherApp()
    ui.setupUi(WeatherApp)
    WeatherApp.show()
    sys.exit(app.exec())
